"""Simple localization helpers for the TorreTray Telegram bot."""

from __future__ import annotations

SUPPORTED_LANGUAGES = {"en", "it"}

MESSAGES = {
    "en": {
        "language_name": "English",
        "meal_lunch": "Lunch",
        "meal_dinner": "Dinner",
        "cmd_start": "Show welcome message and available commands",
        "cmd_set_preferences": "Set lunch or dinner preferences",
        "cmd_mypreferences": "View your current saved preferences",
        "cmd_clearpreferences": "Clear your saved lunch or dinner preferences",
        "cmd_language": "Choose English or Italian",
        "cmd_unregister": "Unlink this Telegram account",
        "cmd_cancel": "Cancel the current flow",
        "start_registered": "Welcome to TorreTray, {name}.\n\nAvailable commands:\n/set_preferences - Set your preferences for lunch or dinner\n/mypreferences - View your currently saved preferences\n/clearpreferences - Clear your saved preferences for lunch or dinner\n/language - Choose English or Italian\n/unregister - Unlink this Telegram account\n/cancel - Cancel the current flow",
        "start_unregistered": "Welcome to TorreTray.\n\nBefore using the bot, you need to register by sending your full name exactly as it appears in TorreTray.\n\nAvailable commands:\n/language - Choose English or Italian\n/cancel - Cancel the current flow\n\nOnce you are registered, you will also be able to use:\n/set_preferences - Set your preferences for lunch or dinner\n/mypreferences - View your currently saved preferences\n/clearpreferences - Clear your saved preferences for lunch or dinner\n/unregister - Unlink this Telegram account",
        "meal_picker_prompt": "Choose whether you want to set preferences for lunch or dinner.",
        "config_meal_prompt": "Which meal do you want to configure?",
        "registered_user": "Registered user",
        "cancelled": "The current flow was cancelled. Use /set_preferences to start again.",
        "plain_help": "Use /set_preferences to set meal preferences. If you need to stop a flow, use /cancel.",
        "not_linked": "Your Telegram account is not linked yet. Send me your full name exactly as it appears in TorreTray to register.",
        "send_full_name": "Please send your full name.",
        "cannot_determine_telegram": "Could not determine your Telegram account.",
        "registration_retry": "{detail}\n\nPlease try again with the exact full name used in TorreTray.",
        "registration_completed": "Registration completed for {name}.\nChoose the meal you want to configure.",
        "setting_preferences_for": "Setting preferences for today's {meal}.",
        "blocked_prefix": "{message}",
        "no_sections": "This meal does not have configurable sections right now.",
        "no_active_flow": "There is no active preference flow. Use /set_preferences to start again.",
        "step_not_active": "This step is no longer active. Use the most recent buttons or restart with /set_preferences.",
        "invalid_option": "That option is no longer valid.",
        "confirm_preferences": "These are your {meal} preferences for {date}:\n\n{summary}\n\nConfirm to save them or cancel to discard.",
        "preferences_saved": "Preferences saved successfully.\n\n{summary}",
        "section_single_prompt": "Section {index}/{total}: {section}\n\nOption: {option}\nWould you like to include this section?",
        "section_multi_prompt": "Section {index}/{total}: {section}\n\nChoose one option or tap 'No {section}'.\n{options}",
        "ack_no": "{section}: No {section}",
        "ack_yes": "{section}: {dish}",
        "view_preferences_prompt": "Which saved preferences would you like to view?\n\nRegistered user: {name}",
        "clear_preferences_prompt": "Which saved preferences would you like to clear?\n\nRegistered user: {name}",
        "clear_preferences_confirm": "Do you want to clear your saved {meal} preferences for {date}?",
        "preferences_cleared": "Saved {meal} preferences cleared.",
        "clear_preferences_cancelled": "No saved preferences were cleared.",
        "current_preferences_header": "Current {meal} preferences for {date}:",
        "no_reservation_for_view": "No {meal} reservation was found for today, so there are no saved preferences to show.",
        "no_saved_preferences": "No preferences are currently saved for today's {meal}.",
        "preferences_without_sections": "Preferences exist for today's {meal}, but they do not contain any section selections.",
        "ticket_printed": "Ticket already printed.",
        "unknown": "Unknown",
        "language_prompt": "Choose the language you prefer for bot messages.",
        "language_updated": "Language updated to {language_name}.",
        "language_requires_registration": "Please register first so I can save your preferred language.",
        "unregister_prompt": "Do you want to unlink this Telegram account so you can register again later?",
        "unregister_done": "Your Telegram account has been unlinked. You can now register again by sending your full name.",
        "unregister_requires_registration": "You are not registered right now, so there is nothing to unlink.",
        "nothing_saved": "Nothing was saved. Use /set_preferences to start again.",
        "view_saved_lunch": "View saved lunch preferences",
        "view_saved_dinner": "View saved dinner preferences",
        "button_lunch": "Lunch",
        "button_dinner": "Dinner",
        "button_yes": "Yes",
        "button_no": "No",
        "button_confirm": "Confirm",
        "button_cancel": "Cancel",
        "button_no_section": "No {section}",
        "button_no_preference": "No preference",
        "button_language_english": "English",
        "button_language_italian": "Italian",
        "summary_no_preference": "No preference",
        "button_unregister": "Unregister",
    },
    "it": {
        "language_name": "Italiano",
        "meal_lunch": "Pranzo",
        "meal_dinner": "Cena",
        "cmd_start": "Mostra il benvenuto e i comandi disponibili",
        "cmd_set_preferences": "Imposta le preferenze di pranzo o cena",
        "cmd_mypreferences": "Vedi le preferenze salvate",
        "cmd_clearpreferences": "Cancella le preferenze salvate di pranzo o cena",
        "cmd_language": "Scegli inglese o italiano",
        "cmd_unregister": "Scollega questo account Telegram",
        "cmd_cancel": "Annulla il flusso corrente",
        "start_registered": "Benvenuto in TorreTray, {name}.\n\nComandi disponibili:\n/set_preferences - Imposta le preferenze per pranzo o cena\n/mypreferences - Vedi le preferenze attualmente salvate\n/clearpreferences - Cancella le preferenze salvate di pranzo o cena\n/language - Scegli inglese o italiano\n/unregister - Scollega questo account Telegram\n/cancel - Annulla il flusso corrente",
        "start_unregistered": "Benvenuto in TorreTray.\n\nPrima di usare il bot, devi registrarti inviando il tuo nome completo esattamente come appare in TorreTray.\n\nComandi disponibili:\n/language - Scegli inglese o italiano\n/cancel - Annulla il flusso corrente\n\nDopo la registrazione potrai usare anche:\n/set_preferences - Imposta le preferenze per pranzo o cena\n/mypreferences - Vedi le preferenze attualmente salvate\n/clearpreferences - Cancella le preferenze salvate di pranzo o cena\n/unregister - Scollega questo account Telegram",
        "meal_picker_prompt": "Scegli se vuoi impostare le preferenze per il pranzo o per la cena.",
        "config_meal_prompt": "Per quale pasto vuoi impostare le preferenze?",
        "registered_user": "Utente registrato",
        "cancelled": "Il flusso corrente e' stato annullato. Usa /set_preferences per ricominciare.",
        "plain_help": "Usa /set_preferences per impostare le preferenze del pasto. Se vuoi interrompere il flusso, usa /cancel.",
        "not_linked": "Il tuo account Telegram non e' ancora collegato. Inviami il tuo nome completo esattamente come appare in TorreTray per registrarti.",
        "send_full_name": "Per favore invia il tuo nome completo.",
        "cannot_determine_telegram": "Non sono riuscito a determinare il tuo account Telegram.",
        "registration_retry": "{detail}\n\nRiprova con il nome completo esatto usato in TorreTray.",
        "registration_completed": "Registrazione completata per {name}.\nScegli il pasto che vuoi configurare.",
        "setting_preferences_for": "Sto impostando le preferenze per {meal} di oggi.",
        "blocked_prefix": "{message}",
        "no_sections": "Questo pasto non ha sezioni configurabili in questo momento.",
        "no_active_flow": "Non c'e' un flusso attivo. Usa /set_preferences per ricominciare.",
        "step_not_active": "Questo passaggio non e' piu' attivo. Usa i pulsanti piu' recenti oppure riavvia con /set_preferences.",
        "invalid_option": "Questa opzione non e' piu' valida.",
        "confirm_preferences": "Queste sono le tue preferenze per {meal} del {date}:\n\n{summary}\n\nConferma per salvarle oppure annulla per scartarle.",
        "preferences_saved": "Preferenze salvate con successo.\n\n{summary}",
        "section_single_prompt": "Sezione {index}/{total}: {section}\n\nOpzione: {option}\nVuoi includere questa sezione?",
        "section_multi_prompt": "Sezione {index}/{total}: {section}\n\nScegli un'opzione oppure premi 'No {section}'.\n{options}",
        "ack_no": "{section}: No {section}",
        "ack_yes": "{section}: {dish}",
        "view_preferences_prompt": "Quali preferenze salvate vuoi vedere?\n\nUtente registrato: {name}",
        "clear_preferences_prompt": "Quali preferenze salvate vuoi cancellare?\n\nUtente registrato: {name}",
        "clear_preferences_confirm": "Vuoi cancellare le preferenze salvate per {meal} del {date}?",
        "preferences_cleared": "Preferenze salvate di {meal} cancellate.",
        "clear_preferences_cancelled": "Nessuna preferenza salvata e' stata cancellata.",
        "current_preferences_header": "Preferenze attuali di {meal} per il {date}:",
        "no_reservation_for_view": "Non e' stata trovata nessuna prenotazione per {meal} oggi, quindi non ci sono preferenze salvate da mostrare.",
        "no_saved_preferences": "Al momento non ci sono preferenze salvate per {meal} di oggi.",
        "preferences_without_sections": "Esistono preferenze per {meal} di oggi, ma non contengono selezioni di sezione.",
        "ticket_printed": "Ticket gia' stampato.",
        "unknown": "Sconosciuto",
        "language_prompt": "Scegli la lingua che preferisci per i messaggi del bot.",
        "language_updated": "Lingua aggiornata in {language_name}.",
        "language_requires_registration": "Registrati prima, cosi' posso salvare la tua lingua preferita.",
        "unregister_prompt": "Vuoi scollegare questo account Telegram cosi' potrai registrarti di nuovo in seguito?",
        "unregister_done": "Il tuo account Telegram e' stato scollegato. Ora puoi registrarti di nuovo inviando il tuo nome completo.",
        "unregister_requires_registration": "Al momento non sei registrato, quindi non c'e' nulla da scollegare.",
        "nothing_saved": "Non e' stato salvato nulla. Usa /set_preferences per ricominciare.",
        "view_saved_lunch": "Vedi preferenze pranzo",
        "view_saved_dinner": "Vedi preferenze cena",
        "button_lunch": "Pranzo",
        "button_dinner": "Cena",
        "button_yes": "Si'",
        "button_no": "No",
        "button_confirm": "Conferma",
        "button_cancel": "Annulla",
        "button_no_section": "No {section}",
        "button_no_preference": "Nessuna preferenza",
        "button_language_english": "Inglese",
        "button_language_italian": "Italiano",
        "summary_no_preference": "Nessuna preferenza",
        "button_unregister": "Scollega",
    },
}


def normalize_language(language: str | None) -> str:
    """Return a supported language code, defaulting to English."""
    if language in SUPPORTED_LANGUAGES:
        return language
    return "en"


def infer_language(telegram_language_code: str | None) -> str:
    """Infer the starting bot language from Telegram when possible."""
    if telegram_language_code and telegram_language_code.lower().startswith("it"):
        return "it"
    return "en"


def t(language: str, key: str, **kwargs: object) -> str:
    """Translate one message key with optional placeholders."""
    selected_language = normalize_language(language)
    template = MESSAGES[selected_language].get(key, MESSAGES["en"][key])
    return template.format(**kwargs)
